### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by JohnMagdy** [Ahmad45123/ExtremeStudio#25]
Hello Dude, so iam Facing some issues with the Plugins Manager while i was trying to install 'Color Picker'.

Debug Logs:
```System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ExtremeStudio.EsPluginsForm.installBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ExtremeStudio
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/ExtremeStudio.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 12.0.51209.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Windows.Forms.Ribbon35
    Assembly Version: 3.5.8.0
    Win32 Version: 3.5.8.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/System.Windows.Forms.Ribbon35.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.11.0.0
    Win32 Version: 2.11.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
ExtremeCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/ExtremeCore.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/Newtonsoft.Json.DLL
----------------------------------------
DotNetZip
    Assembly Version: 1.10.1.0
    Win32 Version: 1.10.1
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/DotNetZip.DLL
----------------------------------------
HotkeyControl
    Assembly Version: 1.0.2410.23277
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/HotkeyControl.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.102.0
    Win32 Version: 1.0.102.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
ScintillaNET
    Assembly Version: 3.5.10.0
    Win32 Version: 3.5.10.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/ScintillaNET.DLL
----------------------------------------
AutocompleteMenu-ScintillaNET
    Assembly Version: 1.3.4.0
    Win32 Version: 1.3.4.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/AutocompleteMenu-ScintillaNET.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light
    Assembly Version: 2.11.0.0
    Win32 Version: 2.11.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light.DLL
----------------------------------------
ExtremeParser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e09036f2e7a192b/ExtremeParser.DLL
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
![capture](https://user-images.githubusercontent.com/19735243/40140000-fde11382-5951-11e8-901e-6ec5f43e80af.JPG)

**Comment by Ahmad45123** [comment]
Whole plugin system shall be reviewed later in 3.1.0
