### ISSUE TITLE
Suggestions&Bug Reports

### ISSUE THREAD

**Issue by JohnMagdy** [Ahmad45123/ExtremeStudio#26]
Hello @Ahmad45123, so iam facing some problems with ExtremeStudio's Hotkeys(Next Search Result Button, Previous Search Result Button) aren't working even i had changed them to Next = F3|None and Previous = F4|None. I tried too changing the default ExtremeStudio's Hotkeys from My ExtremeStudio Folder/config/hotkeys.json but nothing gets solved... and the 'Installed Plugins' Button's Icon is missing or corrupted. #25 

__**Suggestions:**__
* Add Highlighting Feature for 'default', 'bool' statements.
* Add Search History smilliar to Notepad++.
* Add Undo/Redo Buttons.
* Check for existing Plugins/Includes before executing&showing the Plugins/Includes Manager Dialog.
* Launch ExtremeStudio Directly without showing that 'Create Project/Load Project' Dialog when i do the following 'right click -> Open with -> ExtremeStudio' on any Pawn file to Edit/Compile it, smilliar to Original Pawno.
* Add an Timer to check whether iam doing Right click on a folder/file or not and check if the folder contains an Pawn file or the File is a Pawn file and if the result came true Add an Context Menu Item with the following Text 'Open With Extreme Studio' or 'Create ExtremeStudio Project' (if it's an Folder).

**Comment by JohnMagdy** [comment]
and please it 'd be great to try catching/handing Compiler Exceptions smilliar to: pawncc.exe isn't responding. because iam facing some runtime errors recently error 17: "Invalid/unsupported P-code file format" without being notfified  before executing the script about the problem and my current compiled script file(.amx file)'s size is 0KB....

**Comment by JohnMagdy** [comment]
* ***After Last Project Update(Which was released today)*** , i was trying to Load my Project's resource files but suddenly i received the following `SQLite.Interop.dll` exception:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize()
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at ExtremeStudio.SqLiteDatabase.ExecuteScalar(String sql)
   at ExtremeStudio.CurrentProjectClass.ReadInfo()
   at ExtremeStudio.StartupForm.pathTextBox_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.TextBoxBase.set_Text(String value)
   at System.Windows.Forms.TextBox.set_Text(String value)
   at ExtremeCore.PathTextBox.BrowseBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ExtremeStudio
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/ExtremeStudio.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Windows.Forms.Ribbon35
    Assembly Version: 3.5.8.0
    Win32 Version: 3.5.8.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/System.Windows.Forms.Ribbon35.DLL
----------------------------------------
ExtremeCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/ExtremeCore.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/Newtonsoft.Json.DLL
----------------------------------------
DotNetZip
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/DotNetZip.DLL
----------------------------------------
HotkeyControl
    Assembly Version: 1.0.2410.23277
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/HotkeyControl.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.108.0
    Win32 Version: 1.0.108.0
    CodeBase: file:///C:/Users/BrownTurbo%20Gaming/AppData/Local/Apps/2.0/PXN2ZDYZ.9V1/1R4TNCCA.PJW/extr..tion_0000000000000000_0001.0000_6e0903712f7838ab/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.```
![capture2](https://user-images.githubusercontent.com/19735243/40669956-74a48eac-6368-11e8-80c8-8dd171383dd0.JPG)

**Comment by Ahmad45123** [comment]
Did you try starting the app again after the update ?
